name: zen
description: "Zen Puzzle"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.1+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  diacritic: ^0.1.3
  dotted_border: ^2.0.0+2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3
  nsd: ^1.5.3
  pixelarticons: ^0.1.0
  cupertino_icons: ^1.0.2
  collection: ^1.16.0
  google_fonts: ^3.0.1
  device_preview: ^1.1.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.1+1
  flutter_native_splash: ^2.2.7
  url_launcher: ^6.1.5

  lottie: ^2.1.0
  confetti: ^0.7.0
  flip_card: ^0.6.0


  soundpool: ^2.3.0








dependency_overrides:
  nsd_android: ^1.2.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  lint: ^1.8.2


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/logo.png"



# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icon/logo.png
    - assets/images/.
    - assets/brain_animation.json
  fonts:
    - family: Crackman
      fonts:
        - asset: assets/fonts/crackman.ttf
          weight: 700
    - family: Koulen
      fonts:
        - asset: assets/fonts/Koulen-Regular.ttf
          weight: 400


flutter_native_splash:
  color: '#191c1d'
  image: 'assets/icon/logo.png'
  android_12:
    color: '#191c1d'
    image: 'assets/icon/logo.png'